# Generated by Django 5.0.6 on 2024-06-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='static/img/videos/')),
                ('Categoria', models.BooleanField(default=True)),
            ],
        ),
    ]
