# Generated by Django 5.0.6 on 2024-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='Link',
            field=models.URLField(default='https://www.youtube.com/'),
            preserve_default=False,
        ),
    ]
