# Generated by Django 5.0.6 on 2024-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0002_rename_categoria_multimedia_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='Link',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
