# Generated by Django 5.0.6 on 2024-07-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0006_respuesta_multimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='multimedia',
        ),
    ]
