# Generated by Django 5.0.6 on 2024-07-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0007_remove_respuesta_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Multimedia.comentario'),
        ),
    ]
