# Generated by Django 5.0.6 on 2024-07-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0008_respuesta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='multimedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Multimedia.multimedia'),
        ),
    ]
